"""Stub for picocrypto.signing.bip137 (Cython)."""

def bip137_signed_message_hash(message: bytes) -> bytes: ...
def bip137_sign_message(privkey: bytes, message: bytes) -> bytes: ...
def bip137_verify_message(
    message: bytes, signature_b64: bytes | str, pubkey: bytes
) -> bool: ...
