# Stubs for cycrypto.curves.ed25519 (Cython extension)
def ed25519_public_key(seed: bytes) -> bytes: ...
def ed25519_sign(message: bytes, seed: bytes) -> bytes: ...
def ed25519_verify(message: bytes, signature: bytes, public_key: bytes) -> bool: ...
