# Stubs for cycrypto.curves.secp256k1 (Cython extension)
def privkey_to_pubkey(privkey: bytes) -> bytes: ...
def recover_pubkey(msg_hash: bytes, r: int, s: int, recid: int) -> bytes: ...
def sign_recoverable(privkey: bytes, msg_hash: bytes) -> tuple[int, int, int]: ...
def privkey_to_address(privkey: bytes) -> str: ...
